package dev.nomadicprogrammer.spendly.ui.theme
import androidx.compose.ui.graphics.Color
import kotlin.math.max
import kotlin.random.Random

val md_theme_light_primary = Color(0xff92c891)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFACF4A2)
val md_theme_light_onPrimaryContainer = Color(0xFF002203)
val md_theme_light_secondary = Color(0xFF4858A9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDEE1FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001258)
val md_theme_light_tertiary = Color(0xFF006783)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCE9FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F2A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xffda897e)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xffe9ece7)
val md_theme_light_onSurfaceVariant = Color(0xFF42493F)
val md_theme_light_outline = Color(0xFF73796F)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFF91D888)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xff85a784)
val md_theme_light_outlineVariant = Color(0xFFC2C8BD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF91D888)
val md_theme_dark_onPrimary = Color(0xFF003907)
val md_theme_dark_primaryContainer = Color(0xFF0C5313)
val md_theme_dark_onPrimaryContainer = Color(0xFFACF4A2)
val md_theme_dark_secondary = Color(0xFFB9C3FF)
val md_theme_dark_onSecondary = Color(0xFF142778)
val md_theme_dark_secondaryContainer = Color(0xFF2F4090)
val md_theme_dark_onSecondaryContainer = Color(0xFFDEE1FF)
val md_theme_dark_tertiary = Color(0xFF63D3FF)
val md_theme_dark_onTertiary = Color(0xFF003545)
val md_theme_dark_tertiaryContainer = Color(0xFF004D63)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCE9FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF42493F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C8BD)
val md_theme_dark_outline = Color(0xFF8C9388)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF2A6B29)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF91D888)
val md_theme_dark_outlineVariant = Color(0xFF42493F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFB7D9AE)
fun randomPastelColor(): Color {
    // Generate random RGB values in the range of 200-255 to get pastel colors
    val red = Random.nextInt(200, 256)
    val green = Random.nextInt(200, 256)
    val blue = Random.nextInt(200, 256)
    return Color(red, green, blue)
}

fun Color.darken(factor: Float = 0.6f): Color {
    val cofactor = 1 + factor
    val r = max((this.red * 255 * cofactor).toInt(), 0)
    val g = max((this.green * 255 * cofactor).toInt(), 0)
    val b = max((this.blue * 255 * cofactor).toInt(), 0)
    return Color(r, g, b, 255)
}

